Fix support for long non-residential symlinks
fox-it/dissect.xfs pull request #35
Opened 2024-10-14 13:46 UTC by twiggler

The targets of  non-residential symlinks were not completely read. This is because the size of the symlink header was not taken into account on XFS version 5. 

Added a test with a very long symlink and also check number of blocks. 

Bonus:
- Modernize typings

Closes #34

2024-10-14 14:38 UTC, Schamper requested changes

2024-10-14 14:38 UTC, Schamper commented on dissect/xfs/xfs.py
> +    def walk_tree(self, fsb: int, magic: list[int] | None = None, small: bool = False):
Can you add a return type here?

2024-10-14 14:38 UTC, Schamper commented on dissect/xfs/xfs.py
>      ):
And here?

2024-10-14 14:38 UTC, Schamper commented on dissect/xfs/xfs.py
> +                symlink_size = c_xfs.xfs_dsymlink_hdr.size + self.size
```suggestion
                symlink_size = len(c_xfs.xfs_dsymlink_hdr) + self.size
```
Achieves the same but is a bit more readable.

2024-10-15 08:30 UTC, Schamper requested changes

2024-10-15 08:30 UTC, Schamper commented on tests/data/.gitattributes
While it's maybe a bit nicer to have this file in `tests/data`, it's more consistent with other dissect projects to have it in the project root instead.

2024-10-17 07:18 UTC, twiggler commented on tests/data/.gitattributes
Apparently there already was a `.gitattributes` in the project root, so it is also more consistent with this project :)
Fixed.

2024-10-17 09:03 UTC, Schamper approved these changes

2024-10-17 09:14 UTC, pyrco approved these changes

2024-10-17 14:22 UTC, merged